from ketisdk.import_basic_utils import *
from _typeshed import Incomplete
from kpick.pick.base_grasp_detection import BaseGraspDetector as BaseGraspDetector

MODULE_DIR: Incomplete

def get_default_suction_args(): ...

ALL_PAD_SIZES: Incomplete

class SuctionDetector(BaseGraspDetector):
    RPN: Incomplete
    def init(self, net_args, rpn_args: Incomplete | None = ..., net_train_args: Incomplete | None = ..., train: bool = ...) -> None: ...
    def find_suction_candidates(self, rgbd, net_args): ...
    def get_suction_in_workspace(self, rgbd, Suction, all_boxes): ...
    def remove_suction_on_background(self, rgbd, Suction, all_boxes, net_args): ...
    def wrap_suction_from_boxes(self, rgbd, all_boxes): ...
    def score_suction(self, array, all_boxes, model, net_args): ...
    def average_score_suction(self, rgbd, Suction, net_args): ...
    def sort_suction(self, Suction): ...
    def detect_suctions_size(self, array, smooth: bool = ...) -> None: ...
    def detect_suctions_conv(self, rgbd, net_args, remove_bg: bool = ..., smooth: bool = ..., show_time: bool = ...): ...
    gidx: Incomplete
    def detect_suctions_sliding(self, rgbd, net_args, remove_bg: bool = ...): ...
    def select_best_n_suctions(self, Suction, net_args, n: int = ...): ...
    def detect_suctions_sliding_rpn(self, rgbd, net_args, rpn_args, remove_bg: bool = ..., smooth: bool = ...): ...
    def detect_suctions_conv_rpn(self, rgbd, net_args, rpn_args, remove_bg: bool = ..., smooth: bool = ...): ...
    def detect_suctions(self, rgbd, net_args, rpn_args, remove_bg: bool = ...): ...
    def show_suctions(self, rgbd, det, net_args, args, disp_mode: str = ..., out: Incomplete | None = ...): ...
    def detect_and_show_suctions(self, rgbd, net_args, rpn_args, args, remove_bg: bool = ..., disp_mode: str = ..., detected: Incomplete | None = ...): ...
    def detect_and_show_step0(self, rgbd, disp_mode: str = ...): ...
    def detect_and_show_step1(self, rgbd, disp_mode: str = ...): ...
    def detect_and_show_step2(self, rgbd, disp_mode: str = ...): ...
    def showScore(self, rgbd, Score, Loc, disp_mode: str = ...): ...

def get_suction_detector_obj(Detector=..., default_args=...): ...
def get_suction_detector_gui(DetectorObj=...): ...
def demo_suction_gui(title: str = ..., DetectorGui=..., default_args=..., cfg_path: Incomplete | None = ..., default_cfg_path: str = ..., sensors=..., key_args=..., data_root: Incomplete | None = ..., rgb_formats: Incomplete | None = ..., depth_formats: Incomplete | None = ...) -> None: ...
