from _typeshed import Incomplete
from kpick.pick.suction.suction_detection import SuctionDetector as SuctionDetector, demo_suction_gui as demo_suction_gui, get_default_suction_args as get_default_suction_args, get_suction_detector_gui as get_suction_detector_gui, get_suction_detector_obj as get_suction_detector_obj

def get_default_suction_points_args(): ...

class SuctionPointsDetector(SuctionDetector):
    def select_best_n_suctions_2points(self, Suction, net_args, n: int = ...): ...
    def show_suctions_2points(self, rgbd, det, net_args, args, disp_mode: str = ..., out: Incomplete | None = ...): ...
    def detect_suctions_2points(self, rgbd, net_args, rpn_args, remove_bg: bool = ..., smooth: bool = ...): ...
    def detect_and_show_suctions_2points(self, rgbd, net_args, rpn_args, args, remove_bg: bool = ..., disp_mode: str = ..., detected: Incomplete | None = ...): ...

def get_suction_points_detector_gui(DetectorObj=...): ...
