from _typeshed import Incomplete
from kpick.base.base import BasDetectObj as BasDetectObj, DetGui as DetGui

def get_mask_prop(mask): ...
def ring_like(mask, ring_thick: int = ...): ...

class GripInnerDetector(BasDetectObj):
    def get_model(self) -> None: ...
    def get_mask(self, rgbd): ...
    def get_grip(self, rgbd): ...
    def get_grip_and_show(self, rgbd, disp_mode: str = ..., detected: Incomplete | None = ...): ...
    def get_mask_and_show(self, rgbd, disp_mode: str = ...): ...

class GripInnerDetectorGui(GripInnerDetector, DetGui):
    def gui_process_single(self, rgbd, method_ind: int = ..., filename: str = ..., disp_mode: str = ..., detected: Incomplete | None = ...): ...
