from ketisdk.import_basic_utils import *
from _typeshed import Incomplete
from imutils import rotate as rotate, rotate_bound as rotate_bound
from kpick.detectron2_detector import DetectronDetector as DetectronDetector
from kpick.pick.base_grasp_detection import BaseGraspDetector as BaseGraspDetector

DEFAULT_CHECKPOINT_LINK: str

def get_base_inner_grip_cfg(): ...

class InnerGripDetector(DetectronDetector):
    inner_grip_model: Incomplete
    def get_model(self, net_args) -> None: ...
    def get_mask(self, rgbd, thresh: float = ...): ...
    def detect_inner_grips(self, rgbd, net_args, thresh: float = ..., best_n: int = ...): ...
    def show_inner_grips(self, rgbd, det, net_args, args, disp_mode: str = ..., out: Incomplete | None = ...): ...

def get_inner_detector_obj(Detector=...): ...
def get_inner_detector_gui(DetectorObj=...): ...

key_args: Incomplete

def demo_inner_grip_gui(title: str = ..., Detector=..., cfg_path: Incomplete | None = ..., default_cfg_path: str = ..., sensors=..., key_args=..., data_root: Incomplete | None = ..., rgb_formats: Incomplete | None = ..., depth_formats: Incomplete | None = ...) -> None: ...
def demo_simple() -> None: ...
