from ketisdk.import_basic_utils import *
from _typeshed import Incomplete

def find_grip_pts(net_args, rgbd_pad, pad_mask, angles, pad_x, pad_y, center, transform: Incomplete | None = ...): ...
def find_grip_candidates_from_edges(rgbd, net_args, transform: Incomplete | None = ...): ...
